# AppVeyor configuration based on https://github.com/guedou/scapy-appveyor/blob/master/appveyor.yml

version: "v0.1.15.dev0-{build}"

environment:

  # Python versions that will be tested
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      ARCH: "32"
      PLAT_NAME: "win32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      ARCH: "64"
      PLAT_NAME: "win-amd64"

# Install requirements
install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  # Installing WinPcap directly does not work,
  # see http://help.appveyor.com/discussions/problems/2280-winpcap-installation-issue
  - cinst nmap
  - refreshenv
  - "%PYTHON%\\python.exe -m pip install Sphinx==1.4.5"
  # Set path
  - "set PYTHONPATH=%APPVEYOR_BUILD_FOLDER%"
  - "set PATH=%APPVEYOR_BUILD_FOLDER%;%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Copy WinPcap libraries so scapy can found them
  - "copy C:\\Windows\\System32\\Npcap\\wpcap.dll %APPVEYOR_BUILD_FOLDER%"
  - "copy C:\\Windows\\System32\\Npcap\\packet.dll %APPVEYOR_BUILD_FOLDER%"
  # Set the proper build program
  - if "%ARCH%"=="32" (call "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall.bat" x86)
  - if "%ARCH%"=="64" (call "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall.bat" amd64)
  # Build and install the library
  - "%PYTHON%\\python.exe setup.py install"

build: off

test_script:
  # Run tests
  #- "%PYTHON%\\python.exe setup.py test"
  # Build the docs
  - "%PYTHON%\\python.exe setup.py doc"

after_test:
  # Build a source artifact
  - "%PYTHON%\\python.exe setup.py sdist"
  # Build a wheel artifact
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*.whl

deploy:
  release: "pysap $(APPVEYOR_REPO_TAG_NAME)"
  provider: GitHub
  auth_token:
    secure: E3woIwT5J6hCuCVvP2u7Pc+r1mS1hG0dGwoYntsNZHXVqZ0V3DiqefqneBmTXmPZ
  artifact: dist\*.whl
  draft: true
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
